### ISSUE TITLE
issues with mpicc and then cannot find hdf5

### ISSUE THREAD

**Issue by christophermaynard** [hpc-io/h5bench#37]
**CMake Build issues**

This is what I have tried so far:

I have tried set CMAKE_C_COMPILER=mpicc and similarly CMAKE_CXX_COMPILER=mpicxx with various levels of success. I have managed to get to make on my Mac laptop and on a linux cluster, but in both instances it doesn't find hdf5. Setting HDF5_ROOT gets partial success. What is the correct way to set mpi compilers and the hdf5 installation.

Thanks,

```
...
```

**Software Environment**
 - version of h5bench: [e.g. 1.0]
 - installed h5bench using: [spack, from source]
 - operating system: [name and version]
 - machine: [Are you running on a supercomputer or public cluster?]
 - version of HDF5: [e.g. 1.12.0]
 - version of VOL-ASYNC: [e.g. 1.13.1]
 - name and version of MPI: [e.g. OpenMPI 4.1.1]

**Additional Information**

Add any other information about the problem here.

**Comment by christophermaynard** [comment]
Trying h5bench from source, version 1.1 of h5bench, 
macosx gcc7.3, mpich3.1 and hdf5 1.8.16
and
linux cluster, intel 19, openMP4.1 and hdf5 1.12.0
Thanks for any help

**Comment by jeanbez** [comment]
Are you using a system version of HDF5 or did you compile it? Have you tried to define the `HDF5_HOME` directory?

**Comment by jeanbez** [comment]
@christophermaynard did you successfully compiled h5bench by setting the `HDF5_HOME` if your HDF5 installation was not in the default system location? If everything was solved, please let us know, otherwise, we will be closing the issue on March 10.

**Comment by jeanbez** [comment]
We believe this issue has been resolved and since we have not heard back, we are closing it.
