### ISSUE TITLE
python wrapper h5bench won't run

### ISSUE THREAD

**Issue by christophermaynard** [hpc-io/h5bench#38]
**Bug Report**

The python h5bench in the function check_parallel compares the command line to the shell environment variable, if they don't match it exits with the error print('You should not call MPI directly when running h5bench.') command[0]=/bin/sh and shell=/bin/sh
**To Reproduce**

How are you building/running h5bench?

```
slurm batch job on a cray, (with no srun command).
```

What is the input configuration file you use?

```bash
Doesn't get that far!
```

**Expected Behavior**

**Software Environment**

 - version of h5bench: 1.1
 - installed h5bench using: from source
 - operating system: Linux ln04 4.12.14-197.78_9.1.64-cray_shasta_c #1 SMP Wed Aug 25 14:56:40 UTC 2021 (4e2a900) x86_64 x86_64 x86_64 GNU/Linux - 
 - machine: Supercomputer Archer2 www.archer2.ac.uk
 - version of HDF5: [e.g. 1.12.0]
 - version of VOL-ASYNC: [e.g. 1.13.1]
 - name and version of MPI: [e.g. OpenMPI 4.1.1]

**Additional information**

Add any other information about the problem here.

**Comment by jeanbez** [comment]
@christophermaynard We have made some changes to detect that and avoid users from explicitly calling srun/mpirun in the last released version. Could you confirm it is working?

**Comment by christophermaynard** [comment]
Unfortunately the build no longer works. I cloned the head of the repository but when I try and build I get ...
```
cmake ..
-- The C compiler identification is Clang 11.0.0
-- The CXX compiler identification is Clang 11.0.0
-- Cray Programming Environment 2.7.6 C
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/cray/pe/craype/2.7.6/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Cray Programming Environment 2.7.6 CXX
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/cray/pe/craype/2.7.6/bin/CC - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found MPI_C: /opt/cray/pe/craype/2.7.6/bin/cc (found version "3.1") 
-- Found MPI_CXX: /opt/cray/pe/craype/2.7.6/bin/CC (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
CMake Warning (dev) at CMakeLists.txt:13 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable HDF5_ROOT is set to:

    /opt/cray/pe/hdf5-parallel/1.12.0.3/crayclang/9.1

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found HDF5: Included by compiler wrappers   
-- Using HDF5 version: 
CMake Error at CMakeLists.txt:114 (add_subdirectory):
  The source directory

    /work/n02/n02/cmaynard/H5bench/h5bench/amrex

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:144 (add_subdirectory):
  The source directory

    /work/n02/n02/cmaynard/H5bench/h5bench/openpmd

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
```

**Comment by jeanbez** [comment]
@christophermaynard Are you still having issues after a clean build or was your problem solved? If everything was solved, please let us know, otherwise, we will be closing the issue on March 10.

**Comment by jeanbez** [comment]
We believe this issue has been resolved and since we have not heard back, we are closing it.
