### ISSUE TITLE
benchmarks won't complete as file not found.

### ISSUE THREAD

**Issue by christophermaynard** [hpc-io/h5bench#39]
**Benchmarks won't as file not found.**
The benchmarks start but each one exits with file not found, but it doesn't tell me which file. I used the configuration.json file which comes with the 1.1 release. For write, perhaps I need to provide the file? but what and where? For the write, well surely it should be writing the file!

This is the error I am facing during installation:

```
 ls
configuration-h5bench.log  configuration.json  configuration.json~  full-teste	job.sub  job.sub~  slurm-1038041.out  test.py
cmaynard@ln04:/work/n02/n02/cmaynard/H5bench/h5bench-1.1/bench_run> cd full-teste/
cmaynard@ln04:/work/n02/n02/cmaynard/H5bench/h5bench-1.1/bench_run/full-teste> ls
09dd69c2  1cbd24b9  1f4c48f4  249077b6	59d50b3c  61bee9fa  9411e16c  98ad11ae	b149e8ef  e373db41  f942bfa8
cmaynard@ln04:/work/n02/n02/cmaynard/H5bench/h5bench-1.1/bench_run/full-teste> more 09dd69c2/stderr 
slurmstepd: error: execve(): h5bench_write: No such file or directory
slurmstepd: error: execve(): h5bench_write: No such file or directory
slurmstepd: error: execve(): h5bench_write: No such file or directory
slurmstepd: error: execve(): h5bench_write: No such file or directory
srun: error: nid004833: tasks 0-3: Exited with exit code 2
srun: launch/slurm: _step_signal: Terminating StepId=1038041.
```
Thanks for any help.
**Software Environment**
 - version of h5bench: [e.g. 1.0]
 - installed h5bench using: [spack, from source]
 - operating system: [name and version]
 - machine: [Are you running on a supercomputer or public cluster?]
 - version of HDF5: [e.g. 1.12.0]
 - version of VOL-ASYNC: [e.g. 1.13.1]
 - name and version of MPI: [e.g. OpenMPI 4.1.1]

**Additional Information**

Add any other information about the problem here.

**Comment by yzanhua** [comment]
I had the same problem. The error message says no file called h5bench_write. "h5bench_write" is located at the same place as the file "h5bench" (i.e. the build directory).
I fixed this issue by adding the build directory to PATH.

**Comment by jeanbez** [comment]
@christophermaynard and @yzanhua we fixed that in the main branch, could you confirm you are not still facing this issue?

**Comment by yzanhua** [comment]
@jeanbez I am still facing this issue if I call h5bench from another directory different from the build directory.
For example the following does not work:
```shell
# mkdir ~/test
# cd ~/test
# /path-to-h5bench-build-directory/h5bench --debug configuration.json
```
I see in the "h5bench" python script that there is a "PREFIX" appended before "H5BENCH_PATTERNS_WRITE". But it seems no one will modify "PREFIX" .

**Comment by jeanbez** [comment]
@yzanhua so the directory where you installed h5bench is not in the global path, correct? If that is the case, the script with not find the executables if you are not launching it from the directory where it was built. I'll update the documentation to clarify that.

**Comment by yzanhua** [comment]
@jeanbez Yes. Adding the build directory to the global path helps me solve the issue. Thank you for the clarification.
